{"name": "test_authorization_with_invalid_credentials_negative", "status": "passed", "description": "In that test we try login with invalid credentials", "start": 1658397469942, "stop": 1658397499665, "uuid": "e5d4204c-83cc-4f51-b5f9-ee33a1be92aa", "historyId": "c1c8d9ab315ced79f61d6f2b0f6dbe24", "testCaseId": "99b3d4031e3c9193204afd98901cc2c8", "fullName": "tests.negative_tests.test_authorization_user_negative.TestAuthorizationRegistrationNegative#test_authorization_with_invalid_credentials_negative", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "tag", "value": "@pytest.mark.usefixtures('set_up_webdriver')"}, {"name": "parentSuite", "value": "tests.negative_tests"}, {"name": "suite", "value": "test_authorization_user_negative"}, {"name": "subSuite", "value": "TestAuthorizationRegistrationNegative"}, {"name": "host", "value": "vladislav-G3-3579"}, {"name": "thread", "value": "60681-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.negative_tests.test_authorization_user_negative"}]}